### ISSUE TITLE
SimplePropertyRole  Search API queries

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#1]
Hi,

Do we have any documentation available so that we can check the possible string values of “PropertyTypes”,” RoleTypes” , “Tags”, “RoleType” “RoleStatus”?

In Dezrez we have featured properties but how to get featured properties from Rezi system. I am using SimplePropertyRole search API to get all properties from REZI system.

Also how to identify rental period of respective property like we have in DezRez system SaleProperty , PricePerMonth?

**Comment by dendle** [comment]
Hello Prashant,

In the Dezrez Core API, each estate agent can have their own, custom enums.  We pre-fill these enums with standard values, but this list can be added to.

To query which enum values are available, use the Enum Suggest endpoint, here:
https://core-api-uat.dezrez.com/Help/Api/GET-api-enum_typeName_systemName_eventCategoryType

I'm just double checking that this can return a list of possible values for a given enum type.

I'll post an example request after my check.

Cheers,
Matt

**Comment by dendle** [comment]
So, to list all property types, the relative URL would be:
api/enum?typeName=PropertyType

And this returns an array of values:
[
  {
    "Id": 514,
    "Name": "Terraced House",
    "SystemName": "TerracedHouse"
  },
  {
    "Id": 515,
    "Name": "End of Terrace House",
    "SystemName": "EndofTerraceHouse"
  },
...
]

**Comment by prashant-v** [comment]
ok..

can you guide for the below points?

In Dezrez we have featured properties but how to get featured properties from Rezi system. I am using SimplePropertyRole search API to get all properties from REZI system.

Also how to identify rental period of respective property like we have in DezRez system SaleProperty , PricePerMonth?

**Comment by dendle** [comment]
The 'Featured' flag comes under the marketing flags enum:
/api/enum?typeName=MarketingFlag

With regards to the rental period query, each property marketing role has a price type enum:
{{url}}/api/enum?typeName=PriceType

I hope this helps.

Cheers,
Matt

**Comment by dendle** [comment]
So to look for featured properties in the search:
POST to /api/simplepropertyrole/search

with the json body
{ 
  "MarketingFlags": ["Featured"]
}

**Comment by prashant-v** [comment]
Thanks Matt. Can we get the MarketingFlags in API response? I can see Tag associated with Properties in API response but not the MarketingFlags

**Comment by marc-harry** [comment]
Hi Prashant, You should be able to get the MarketingFlags from the Flags property on the response.

**Comment by dendle** [comment]
Hi Prashant, I hope this thread has answered your questions in full, and I will now close this issue.

If not, please comment again and I'll open it back up.

Cheers,
Matt
