### ISSUE TITLE
Buyer - Request for viewing property

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#10]
Hello,

We want to implement request for viewing and read viewing details of properties functionality.
Can you guide which API we would need to use for the following:
a. Add a request for viewing property
b. Check and get viewing details of requested viewing.

Thanks,

**Comment by dendle** [comment]
Hi Prashant,

We've written a whitepaper about the endpoints regarding finding a property, and requesting a viewing on it using free/busy functionality.

Look at the [White Papers](https://github.com/dezrez/DezrezCoreAPI/blob/master/WhitePapers.md) section, and look at the bot document.  It details the endpoints that were involved in this process.

As for getting the viewing details, you can get all the viewings for a role here:
[Get Role Viewinngs](https://core-api-dev.dezrez.com/Help/Api/GET-api-role-id-viewings_pageSize_pageNumber_excludeDrafts)

I hope this information helps.

Regards,
Matt Dendle

**Comment by prashant-v** [comment]
Hello,

We can get the details of viewing by viewing id or by property role id. Can you guide how we can get all viewing details by people id or group id?

Thanks

**Comment by dendle** [comment]
Hello Prashant,

Its all stored under the roles, so for the person ID, [get that person](https://core-api-uat.dezrez.com/Help/Api/GET-api-people-id) and enumerate thier groups.  Then, from the group [you get the roles](https://core-api-uat.dezrez.com/Help/Api/GET-api-group-id-roles_pageSize_pageNumber_roleTypes[0]_roleTypes[1]_roleStatuses[0]_roleStatuses[1]), and lastly there is a [role events endpoint](https://core-api-uat.dezrez.com/Help/Api/GET-api-role-id-events_pageSize_pageNumber_branchId_from_to_type[0]_type[1]_eventCategoryType_excludedTypes[0]_excludedTypes[1]_includeDrafts), that gets you all events for a role, those events include viewings.

Also, you can skip the group part by going straight from a person ID to a role:
Person => SearchingRoles [Example endpoint](https://core-api-uat.dezrez.com/Help/Api/GET-api-people-id-searching)

I hope this helps.

Cheers,
Matt

**Comment by prashant-v** [comment]
yes we can get the details with above steps.
Alternatively we observed one API i.e.  get all events by group i.e.https://core-api-dev.dezrez.com/Help/Api/GET-api-group-id-events_pageSize_pageNumber_branchId_from_to_type%5B0%5D_type%5B1%5D_eventCategoryType_activeRolesOnly_propertyId_excludedTypes%5B0%5D_excludedTypes%5B1%5D_roleId_includeDrafts
We are getting booking events associated with group id. So do you think this is a right to get all viewing details of person by group?

Thanks,
