### ISSUE TITLE
Adding a buyer role to Group or member

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#11]
Hello,

Which api we should use to add new buyer role to group or member?

Thanks

**Comment by dendle** [comment]
Hi prashant,
1. Do you mean a prospective buyer? a.k.a Applicant?
2. Or do you mean buyer, as in a person is buying a role?

If 1, you register a searchingRole for them, with some criteria [Here](https://core-api-dev.dezrez.com/Help/Api/POST-api-group-id-savesalessearch)

If 2, a buyer becomes a buyer by getting an offer they made accepted-  They must first [make an offer](https://core-api-dev.dezrez.com/Help/Api/POST-api-offer-recordoffer), and then that [offer must be accepted.](https://core-api-dev.dezrez.com/Help/Api/POST-api-offer-recordofferresponse)

I hope this helps.

Regards,
Matt Dendle

**Comment by dzy969** [comment]
Hi Matt,
After we have created a new group do we have to add a searchingRole for them before we can add a viewing appointment?
If yes, whats the minimum we can add and if not how else can we get/create the roleId

Thanks
Dean

**Comment by dendle** [comment]
Hi Dean,

Sorry or closing this issue too early.

A searching role is not required in order to [make a viewing appointment](https://core-api-uat.dezrez.com/Help/Api/POST-api-viewing-bookviewing).

The property ID and property marketing role ID of the property to view need to be specified, and if you already have a group, you just need to set the ID property of the group JSON:

group: {id:1}

I hope this makes sense.

Cheers,
Matt

**Comment by dzy969** [comment]
Great - We have the propertyID and groupID.
Is the property marketing role ID part of the property object (if so we will already have that) and where do we specify that in bookViewing request, I cant see that in the request documentation.

**Comment by dendle** [comment]
Its just referred to as RoleID in the link above.

Yeah, you should only care about property marketing roles, as these represent the actual sale/let of the property - the property record itself just holds the address and current owner.  So, a property can have multiple roles, and its usually one of these roles (the active sales role) that you are interested in - so just grab that roles ID.

We do need to improve the documentation to explain things a little, its a work in progress :)

I hope this helps,

Matt

**Comment by prashant-v** [comment]
Hello,

We are trying to execute the https://core-api-uat.dezrez.com/Help/Api/POST-api-viewing-bookviewing api but we are facing "Authorization has been denied for this request" error.
Can you please guide for the same?

Thanks,

**Comment by dendle** [comment]
The code changes for this fix are now on UAT - could you please confirm that this is working now?

Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

We are still getting an error : {"Message":"Authorization has been denied for this request."}
Sent you the details about request, please check

Thanks,

**Comment by dendle** [comment]
Hello Prashant,

You need the **event_write** scope for this - the token in the email you sent had these scopes only:

   "impersonate_web_user",
    "property_read",
    "people_read",
    "property_write",
    "people_write",
    "event_read"

**Comment by dendle** [comment]
A good tool to use to find out what scopes are in a token, can be found here:

[JWT.IO](https://jwt.io/)

Hope this helps...

**Comment by prashant-v** [comment]
Hi Matt,

We are executing the book viewing request but we are facing validation error from API.
{"Message":"Viewing Domain Service - Validation has failed for: BookViewing","ErrorReference":"ADS-Val","Details":"See the ValidationErrors list of (1) issues for more details.","ValidationErrors":["Customer info has not been supplied"]}

It is saying “Customer info has not been supplied”, but we just need to pass the property role id and group id of user.
Can you please check the same?

**Comment by marc-harry** [comment]
Hi @prashant-v,

As well as the group Id you also just need to specify the attendee type of group is going on the viewing, in your case here its most likely going to be "Viewer", like so:
`"AttendingGroups": [{
    "Type": {
        "SystemName": "Viewer"
    },
    "Group": {
        "Id": 1
    }
}]`

The Type property can be changed to "Owner" if needed to specify that the group attending the viewing is the owning group of the property. Or you could have two or more groups attending who are of type Viewer/Owner.

I hope this helps,

Marc

**Comment by prashant-v** [comment]
Hello

We tried with passing Type as viewer but this time we are getting 500 internal error
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"a5db8c41-ec40-4d13-a6fd-e2a22b29c81a","Details":"Error occured whilst invoking action BookViewing on controller ViewingController. This error has been logged.","ValidationErrors":null}

Can you please guide for the same?

**Comment by marc-harry** [comment]
Hi,

The error being thrown is due to the api needing to know which branch the viewing is to be associated with. When you make the call to the api can you pass a query parameter called "branchid" and assign it the branch id of the property role that you are requesting the viewing for. That will resolve the error.

Cheers,
Marc

**Comment by prashant-v** [comment]
Hello,

Even passing the branchid as querystring parameter we are getting the same error
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"90f0bddc-02c7-47a0-a8e9-8faba85263a6","Details":"Error occured whilst invoking action BookViewing on controller ViewingController. This error has been logged.","ValidationErrors
Also in the API documentation i havent seen any information of passing branchID.

Thanks
