### ISSUE TITLE
Get All events by group

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#12]
Hello,

We are trying to execute the get all events by group i.e.
https://core-api-dev.dezrez.com/Help/Api/GET-api-group-id-events_pageSize_pageNumber_branchId_from_to_type[0]_type[1]_eventCategoryType_activeRolesOnly_propertyId_excludedTypes[0]_excludedTypes[1]_roleId_includeDrafts
but facing at authorization issue.
{"Message":"Authorization has been denied for this request."}
Can you please check the same?

Thanks

**Comment by dendle** [comment]
Hi Prashant,

Can you double check that you're requesting the event_read and people_read access scopes?

These two permissions should be all that is needed - please let me know if you are requesting these and still encountering problems...

Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

With "event_read " permission I am able to get the details.

Thanks

**Comment by dendle** [comment]
Super, closing this off...
