### ISSUE TITLE
Inconsistent results from api/list/property

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#17]
I'm trying to get all of the properties on the system by using the /api/list/property call.

Since the call supports paging, and I want to limit the payload size, I'm approaching this by requesting pages of data of 100 records each, starting at page 1 and progressing until the set of data returned is empty.

Each time I run my import code - which I've pasted below in case you think it might be hinky - I'm getting 11439 records, but many of the records are duplicates. And the numbers of duplicates are different each time. For three runs done in quick succession, the number of distinct Ids returned were 9146, 8910 and 9311.

I appreciate that this kind of approach isn't guaranteed to return the same results each time, because of possible data changes, but I wouldn't expect to see this level of difference. My guess is that you're not fixing the ordering on the data for the paged calls, so the paging isn't working as expected. Is there any way of specifying the ordering in the API call, so I can use this approach? Or do I need to wait for a bug fix?

Thanks, Ewan

```
            List<RemotePropertyByList> returnProperties = new List<RemotePropertyByList>();
            string accessToken = GetAuthenticationToken();
            int pageSize = 100;
            int pageNumber = 1;

            RemotePropertyList propertyList;
            do
            {
                string callPath = string.Format("list/property?pageSize={0}&pageNumber={1}&agencyID={2}",
                    pageSize,
                    pageNumber,
                    m_AgencyID);

                string filter = @"{ }";
                propertyList = ObjectByPost<RemotePropertyList>(GetHttpClient(accessToken), new Uri(m_BaseUrl), callPath, filter);
                if (propertyList != null && propertyList.Collection != null)
                {
                    returnProperties.AddRange(propertyList.Collection);
                }
                pageNumber++;
            }
            while (propertyList != null && propertyList.Collection != null && propertyList.Collection.Count > 0);
```

**Comment by dendle** [comment]
Hi Ewan,

That endpoint provides sorting abilities - but there appears to be an issue if you dont specify one - By default, the list you are using orders by price.

We should back this default up by having a secondary order by ID, so this doesnt happen.

I'll submit a bug internally, but if you could use the sort option on the endpoint to sort by ID, this problem (hopefully) goes away until then.

HTH,
Matt

**Comment by ewanmceachran** [comment]
Thanks - could you tell me how to do this? I noticed that there were Sort and Order properties on the filter, but these take integers and I don't know what to put in (it's possible that the api/enum call would help me, but I also don't know what to pass to that to get out the values...)

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran have a look here:

http://core-api-uat.dezrez.com/Help/ResourceModel?modelName=PropertyListSort

These aren't system Enums as such so cannot be looked up, however you can add reference them in the API documentation.

If you want to use the sort simply send a property on the POST of type `Sort : 1` for example.

Richard.

**Comment by rjmacarthy** [comment]
You can also order them:

Full list API:
http://core-api-uat.dezrez.com/Help/Api/POST-api-list-property_pageSize_pageNumber

Sort on the list.
http://core-api-uat.dezrez.com/Help/ResourceModel?modelName=ListOrder

Richard.

**Comment by rjmacarthy** [comment]
Closing issue as questions have been answered.
