### ISSUE TITLE
Sorting error on searches across pages.

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#19]
Previously I raised an issue to do with the paging on the api/list/property call. It looks like there are similar issues on other calls, for instance api/list/events, /api/globalsearch/groups. Generally, if there are N unique records, and I make N/p calls for p-sized pages of data, I generally end up with fewer than N unique records in total. Presumably the fault will be the same in each case - failure to have a fallback or secondary sort on a unique field. 

It's also worth mentioning some related odd behaviour on the Rezi web application. I was bouncing back and forth between pages 1 and 2 of active searches - as you do, sometimes you have to make your own fun - and sometimes page 1 would show me one set of data, sometimes another set of data. So my best guess on _that_ is that you have two servers giving back the data, without session affinity, and each is maintaining its own cache of data, and the two have gone out of synch, If true, I guess that this in itself could account for the paging issues.

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran, thanks for bringing this to our attention.

After investigating this issue it appears to be a simple sorting issue.

If you have this issue calling the endpoint yourself, simply add a sort to the results and it should clear up.

Closing off this issue.

Thanks.

Richard.
