### ISSUE TITLE
Get property description

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#2]
Hi,

I am implementing get property description API but while executing API I am getting following message:
{"Message":"Authorization has been denied for this request."}
I am using the property_read permission. I have tried with property_basic_read permission but it was saying invalid scope while getting access token.
Can you guide while scope I need to use to get property description?

Thanks,

**Comment by dendle** [comment]
Hi Prashant,

Looks like you need another permission scope.

Could you tell me the URL of the endpoint you were trying to call?

I'll see what permissions it demands, and make sure you have them.

Thanks,

Matt

**Comment by prashant-v** [comment]
I am using following API endpoint
https://core-api-uat.dezrez.com/api/property/{propertyid}/descriptions?pageSize=1&pageNumber=233

**Comment by dendle** [comment]
Hi Prashant,

I've spotted the problem, and fixed it in the code.  I'll work on getting it to UAT as soon as I can.

Also, I'm interested as to your use of that endpoint - you should already have access to everything to do with the property from the [SimplePropertyRole controller](https://core-api-dev.dezrez.com/Help#SimplePropertyRole).

So, you're already using the [search endpoint](https://core-api-dev.dezrez.com/Help/Api/POST-api-simplepropertyrole-search) -  so you'd take the RoleId of the property you'd like to know more about from the search results, and pass that into '[Full Details](https://core-api-dev.dezrez.com/Help/Api/GET-api-simplepropertyrole-roleId)' endpoint, in the same controller.

The Descriptions property contains all of the available descriptions, and should be available for you to use before the code changes make it to UAT.

Does that help?

Cheers,
Matt

**Comment by prashant-v** [comment]
Hi Matt,

Yes this API return everything that we need instead of giving three different API call to fetch description, documents, images etc.

Thanks

**Comment by dendle** [comment]
Great - sorry you didn't know about that earlier.

Let me know about what kinds of things you'll be doing, and perhaps I could point out some more useful endpoints for you?

Cheers,
Matt
