### ISSUE TITLE
Sales searching criteria

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#22]
Within the 'MustHave' and 'ShouldNotHave' etc. elements in the Criteria element for sales searching criteria there are 'PropertyTags' elements, which contain names and Ids. On the examples that I've looked at, the property tag values look like the values of the 'Town' field in property addresses. Is this the case? If not, how do these property tags relate to the address data?

Also, in all the examples that I've looked at, the 'Region' array (beneath the PropertyTags array) has been empty. What kind of data might we expect to see in there?

Thanks

**Comment by dendle** [comment]
Hi Ewan,
Sorry for the delay - property tags are tags that the agent has invented - like a tag cloud.
They could be anything from "Great local school" to "Swansea".

As for the regions, these refer to well known regions we have imported or the agent has added themselves. See the Region endpoint for more details.

I hope this helps,
Matt
