### ISSUE TITLE
Can't add a group to a property

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#24]
I am calling the URL:

https://api.dezrez.com/api/property/349412/addgrouptoproperty?agencyID=131

I am using GET /api/group/{id} first in order to get the group that I want to add and then I'm passing this in the Group parameter along with ForceUpdate : true and OwnedSince : 2016-09-26T20:05:28+0100

The response I get is:

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"6f5caf34-632f-4f88-a1b9-43411ea39294","Details":"Error occured whilst invoking action AddGroupToProperty on controller PropertyController. This error has been logged.","ValidationErrors":null}

Can I not just pass the group ID in order to link it to a property?

**Comment by rjmacarthy** [comment]
Hi geoff please send us the JSON payload you are using to make the request.

**Comment by tuscan88** [comment]
Is there a way I can send it that isn't public as it contains contact infomation for people in it

**Comment by rjmacarthy** [comment]
Changing the values of the JSON payload is OK, its just the format we are interested in.

**Comment by geoffs3310** [comment]
{
	"Group": {
		"BranchId": 1661815,
		"OwningTeamId": 1661819,
		"Roles": [{
			"GroupId": 1750512,
			"FinancialStatus": null,
			"Origin": {
				"Id": 218709,
				"Name": "Not Specified",
				"SystemName": "NotSpecified"
			},
			"Grade": null,
			"Name": null,
			"RoleType": {
				"Id": 218860,
				"Name": "Interest",
				"SystemName": "Interest"
			},
			"RoleStatus": {
				"Id": 218851,
				"Name": "Active",
				"SystemName": "Active"
			},
			"CustomFields": null,
			"CreatedDate": "2016-09-26T12:26:17Z",
			"CreatedBy": {
				"Initials": "M T",
				"ContactName": "Mr Matthew Turner",
				"Gender": {
					"Id": 218589,
					"Name": "Male",
					"SystemName": "Male"
				},
				"Title": "Mr",
				"FirstName": "Matthew",
				"LastName": "Turner",
				"PrimaryTelephone": null,
				"PrimaryEmail": {
					"Type": {
						"Id": 218422,
						"Name": "Email",
						"SystemName": "Email"
					},
					"Value": "matt@turner.com",
					"Notes": null,
					"ContactOrder": 1,
					"AllowContact": true,
					"Id": 3641629
				},
				"JobTitle": null,
				"Id": 1892816
			},
			"Id": 3057522
		}, {
			"PropertyId": 349409,
			"GroupId": 1750512,
			"FinancialStatus": null,
			"Origin": null,
			"Grade": null,
			"Name": "Joe Bloggs owns",
			"RoleType": {
				"Id": 218856,
				"Name": "Owns",
				"SystemName": "Owns"
			},
			"RoleStatus": {
				"Id": 218851,
				"Name": "Active",
				"SystemName": "Active"
			},
			"CustomFields": [],
			"CreatedDate": "2016-09-26T14:08:44Z",
			"CreatedBy": {
				"Initials": "M T",
				"ContactName": "Mr Matt Turner",
				"Gender": {
					"Id": 218589,
					"Name": "Male",
					"SystemName": "Male"
				},
				"Title": "Mr",
				"FirstName": "Matt",
				"LastName": "Turner",
				"PrimaryTelephone": null,
				"PrimaryEmail": {
					"Type": {
						"Id": 218422,
						"Name": "Email",
						"SystemName": "Email"
					},
					"Value": "matt@turner.com",
					"Notes": null,
					"ContactOrder": 1,
					"AllowContact": true,
					"Id": 3641629
				},
				"JobTitle": null,
				"Id": 1892816
			},
			"Id": 3057625
		}],
		"Address": {
			"Location": {
				"CenterPoint": {
					"Latitude": 53.190555632,
					"Longitude": -2.8935230571,
					"Altitude": 0,
					"Order": 0,
					"Id": 1032402
				},
				"Extent": [],
				"ViewPoints": [],
				"Id": 930702
			},
			"AddressSource": {
				"Id": 218381,
				"Name": "National",
				"SystemName": "National"
			},
			"SourceId": "53797793",
			"OrganizationName": "Someone",
			"Number": "",
			"BuildingName": "Some building",
			"Street": "Some Street",
			"Town": "Chester",
			"Locality": "",
			"County": "Cheshire",
			"Postcode": "CH1 1AA",
			"CreatedDate": "2016-09-07T18:07:55Z",
			"CreatedBy": {
				"Initials": "M T",
				"ContactName": "Mr Matthew Turner",
				"Gender": {
					"Id": 218589,
					"Name": "Male",
					"SystemName": "Male"
				},
				"Title": "Mr",
				"FirstName": "Matthew",
				"LastName": "Turner",
				"PrimaryTelephone": null,
				"PrimaryEmail": {
					"Type": {
						"Id": 218422,
						"Name": "Email",
						"SystemName": "Email"
					},
					"Value": "matt@turner.com",
					"Notes": null,
					"ContactOrder": 1,
					"AllowContact": true,
					"Id": 3641629
				},
				"JobTitle": null,
				"Id": 1892816
			},
			"Id": 1244902
		},
		"RoleCount": 0,
		"Origin": null,
		"Grade": null,
		"Name": "Joe Bloggs",
		"Description": null,
		"GroupType": {
			"Id": 218641,
			"Name": "Individual",
			"SystemName": "Individual"
		},
		"GroupIcon": null,
		"GroupBackgroundImageUrl": null,
		"Notes": null,
		"Members": [{
			"Person": {
				"Gender": {
					"Id": 218589,
					"Name": "Male",
					"SystemName": "Male"
				},
				"Title": "Mr",
				"FirstName": "Joe",
				"LastName": "Bloggs",
				"ContactName": "Mr Joe Bloggs",
				"PrimaryTelephone": {
					"Type": {
						"Id": 218425,
						"Name": "Mobile",
						"SystemName": "Mobile"
					},
					"Value": "07123456789",
					"Notes": null,
					"ContactOrder": 0,
					"AllowContact": false,
					"Id": 3806220
				},
				"PrimaryEmail": {
					"Type": {
						"Id": 218422,
						"Name": "Email",
						"SystemName": "Email"
					},
					"Value": "joebloggs@gmail.com",
					"Notes": null,
					"ContactOrder": 0,
					"AllowContact": true,
					"Id": 3806219
				},
				"Addresses": [{
					"Location": {
						"CenterPoint": {
							"Latitude": 53.190555632,
							"Longitude": -2.8935230571,
							"Altitude": 0,
							"Order": 0,
							"Id": 1032402
						},
						"Extent": [],
						"ViewPoints": [],
						"Id": 930702
					},
					"AddressSource": {
						"Id": 218381,
						"Name": "National",
						"SystemName": "National"
					},
					"SourceId": "53797793",
					"OrganizationName": "Someone",
					"Number": "",
					"BuildingName": "Some building",
					"Street": "Some Street",
					"Town": "Chester",
					"Locality": "",
					"County": "Cheshire",
					"Postcode": "CH11AA",
					"CreatedDate": "2016-09-07T18:07:55Z",
					"CreatedBy": {
						"Initials": "M T",
						"ContactName": "Mr Matthew Turner",
						"Gender": {
							"Id": 218589,
							"Name": "Male",
							"SystemName": "Male"
						},
						"Title": "Mr",
						"FirstName": "Matthew",
						"LastName": "Turner",
						"PrimaryTelephone": null,
						"PrimaryEmail": {
							"Type": {
								"Id": 218422,
								"Name": "Email",
								"SystemName": "Email"
							},
							"Value": "matt@turner.com",
							"Notes": null,
							"ContactOrder": 1,
							"AllowContact": true,
							"Id": 3641629
						},
						"JobTitle": null,
						"Id": 1892816
					},
					"Id": 1244902
				}],
				"ContactItems": [{
					"Type": {
						"Id": 218422,
						"Name": "Email",
						"SystemName": "Email"
					},
					"Value": "joebloggs@gmail.com",
					"Notes": null,
					"ContactOrder": 0,
					"AllowContact": true,
					"Id": 3806219
				}, {
					"Type": {
						"Id": 218425,
						"Name": "Mobile",
						"SystemName": "Mobile"
					},
					"Value": "07123456789",
					"Notes": null,
					"ContactOrder": 0,
					"AllowContact": false,
					"Id": 3806220
				}],
				"Id": 1993113
			},
			"RelationshipType": {
				"Id": 218838,
				"Name": "Primary Group Member",
				"SystemName": "PrimaryGroupMember"
			},
			"Order": 0,
			"Id": 1993113
		}],
		"CustomFields": null,
		"CreatedDate": "2016-09-26T12:26:16Z",
		"CreatedBy": {
			"Initials": "M T",
			"ContactName": "Mr Matthew Turner",
			"Gender": {
				"Id": 218589,
				"Name": "Male",
				"SystemName": "Male"
			},
			"Title": "Mr",
			"FirstName": "Matthew",
			"LastName": "Turner",
			"PrimaryTelephone": null,
			"PrimaryEmail": {
				"Type": {
					"Id": 218422,
					"Name": "Email",
					"SystemName": "Email"
				},
				"Value": "matt@turner.com",
				"Notes": null,
				"ContactOrder": 1,
				"AllowContact": true,
				"Id": 3641629
			},
			"JobTitle": null,
			"Id": 1892816
		},
		"Id": 1750512
	},
	"ForceUpdate": true,
	"OwnedSince": "2016-09-26T20:05:28+0100"
}

**Comment by tuscan88** [comment]
Thinking about it though if the group has already been created and I know its ID then can't I just use the following JSON:

{"Group":{"Id":1750512},"ForceUpdate":true,"OwnedSince":"2016-09-26T20:05:28+0100"}

Basically what I'm asking is what is the minimum information I can pass the link a group id to a product id?

**Comment by rjmacarthy** [comment]
Hi @geoffs3310 the JSON you are using looks fine.  Even the scaled down JSON should also be fine.

The error reports seem to suggest the problem lies with the BranchId.

Please try making the same request using the following URL and let us know how you get on.

`https://api.dezrez.com/api/property/349412/addgrouptoproperty?agencyID=131&BranchId=1661815`

Basically adding the branch id as a parameter also.

**Comment by tuscan88** [comment]
OK thanks that is working now
