### ISSUE TITLE
Can't add group

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#26]
I am calling the following URL:

https://api.dezrez.com/api/group/addgroup?agencyID=131

And passing the following JSON:

{"Name":"Mr and Mrs Dendle","Members":[{"Person":{"Gender":{"SystemName":"Male"},"Title":"Mr","FirstName":"Matthew","LastName":"Dendle","ContactItems":[{"Type":{"SystemName":"Email"},"Value":"matthew.dendle@dezrez.com","Notes":"Added via postman"}]},"RelationshipType":{"SystemName":"PrimaryGroupMember"}}],"GroupType":{"SystemName":"Individual"}}

And getting this response:

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"7a0d7d30-eff6-443b-b357-8d3639d1ebcc","Details":"Error occured whilst invoking action AddGroup on controller GroupController. This error has been logged.","ValidationErrors":null}

**Comment by rjmacarthy** [comment]
Hi @geoffs3310 please add the branch id on the end similar to issue #24 

Richard.

**Comment by tuscan88** [comment]
Yep that worked thanks
