### ISSUE TITLE
How to use api/property/{id}/uploadandattachdocument method

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#27]
Can you explain how the /api/property/{id}/uploadandattachdocument method works please? 

I am using Guzzle to do the http requests and have been sending json for every other call but as this requires a file to be uploaded does all the data have to be sent as multipart data instead of json? Or should the file be uploaded multipart and other parameters sent as json?

**Comment by marc-harry** [comment]
Hi @geoffs3310,

You will need to post to this endpoint using multipart. For the FileStream property to be populated the form key of "uploaded-files" must be provided other other properties just need form keys that match the names on the data contracts.

Cheers,
Marc

**Comment by tuscan88** [comment]
I have got the upload working but the image doesn't seem to be getting attached to the property in the UAT environment. For example I have done a POST request to the following URL:

https://core-api-uat.dezrez.com/api/property/519106/uploadandattachdocument?agencyID=4

With the following multipart data:

{
    [
        [name] => uploaded-files
        [contents] => Resource id #400
        [filename] => 147514062814751406252146.jpg
    ],
    [
        [name] => DocumentType
        [contents] => {"SystemName":"Image"}
    ],
    [
        [name] => DocumentSubType
        [contents] => {"SystemName":"Photo"}
    ],
    [
        [name] => IsPublic
        [contents] => 1
    ]
}

I have received the following response:

{"Url":"https://core-docs-uat.dezrez.com/4/dezrezcoreuat/public/2660710.jpg","RequiresAuthentication":false,"ExpiryDate":null,"Tags":[],"DocumentType":{"Id":1943,"Name":"Image","SystemName":"Image"},"DocumentSubType":{"Id":1925,"Name":"Photo","SystemName":"Photo"},"FileName":"147514062814751406252146","ContentType":"image/jpeg","FileExtension":".jpg","Description":null,"CreatedDate":"2016-09-29T09:54:00.3312632Z","CreatedBy":{"Initials":null,"ContactName":"System Account","Gender":null,"Title":null,"FirstName":"System Account","LastName":null,"PrimaryTelephone":null,"PrimaryEmail":null,"JobTitle":null,"Id":37201},"Id":2660710}

However if I look in property images and photography section for that property there are no images showing.

**Comment by tuscan88** [comment]
This is the same issue as #33 The images need to be attached to a role if the property is being marketed
