### ISSUE TITLE
Typo with client source

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#28]
I've noticed that when adding a client through the rezi control panel there are lots of options for source and there is a typo in one of them. The option value for Recommendation is Remendation.

If I want to say that a client source is recommendation when creating a client through the API shall I pass the same value or will it be fixed?

**Comment by marc-harry** [comment]
Hi @geoffs3310,
I have fixed this spelling issue for this, and the fix should be on the UAT environment shortly. Once there you should be able to pass 'Recommendation' as the source with no problems.
Cheers,
Marc
