### ISSUE TITLE
Can't save text description

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#29]
I am calling the following url:

https://api.dezrez.com/api/TextDescription/save?agencyID=131

And passing the following JSON:

{"Text":"This is the summary","Type":{"Name":"SummaryText","SystemName":"SummaryText"},"Name":"SummaryText","PropertyId":351105,"ForceUpdate":true,"Id":null}

And getting the following response:

{"Message":"Authorization has been denied for this request."}

The scope I am using with my oath token is:

impersonate_web_user property_write property_read event_read event_write people_read people_write document_write document_read

I have tried passing the BranchId parameter as well but the result is the same

**Comment by marc-harry** [comment]
A similar issue appears to have occured as the RoomDescription/save endpoint on other description endpoints. The fix for this has been made and should be available on the UAT environment in the next couple of hours.

Cheers,
Marc
