### ISSUE TITLE
Get a property with an associated role by their Id Error

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#3]
Hello,

I am getting an error while executing following API :https://core-api-dev.dezrez.com/Help/Api/GET-api-simplepropertyrole-roleId.
**Error Details :**
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"f0925e77-c811-44fb-9bfd-1fe93d487940","Details":"Error occured whilst invoking action Get on controller SimplePropertyRoleController. This error has been logged.","ValidationErrors":null}

I am executing  following URL with GET method
https://core-api-uat.dezrez.com/api/simplepropertyrole/{roleID}?AgencyId={agencyid}

Can you please help?

Thanks,

**Comment by prashant-v** [comment]
Also this API doesnt return the  room details associated with property. Can you please guide from where I can get the room details of the property?

**Comment by marc-harry** [comment]
Hi @prashant-v,

With the error you are getting that appears to be due to the fact the apikey isn't being passed as part of the request to get the property with the role id.
To answer your second question, the room details associated with the property will be within the description collection that comes back in the response. You will be able to get the room counts, room details and any other descriptions that are on that properties role.

Cheers,
Marc

**Comment by prashant-v** [comment]
Hi Marc,

Apikey is not any input parameter for this API, it only accepts RoleID parameter. In order to execute API I am passing the Authorization header with bearer scheme. Can you guide where to pass API key?

Thanks

**Comment by marc-harry** [comment]
Hi @prashant-v,

Sorry, yes you don't need to pass in an Api key. Would you be able to send the full url for the roleId and agencyId that you are requesting so that we can investigate this further to see what is happening with that api call in more detail?

Cheers,
Marc

**Comment by prashant-v** [comment]
Hi Marc, 

Sent an email to Matt for additional information about role id and agencyid.

Thanks

**Comment by dendle** [comment]
Hi prashant,

I'm having trouble getting to the bottom of this one!

Could you be so kind as to email me a token that you can reproduce this issue with?

Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

Now I am able to execute proeprty role API. In the response I can see the different type of description.
But in the API documentation you have mentioned the description is of type SimpleWebGatewayDescriptionDataContractBase (i.e. https://core-api-dev.dezrez.com/Help/ResourceModel?modelName=SimpleWebGatewayDescriptionDataContractBase) but I am getting different objects in collection of description fields as follow.

Descriptions":[{"PropertyType":{"DisplayName":"Detached House","SystemName":"DetachedHouse"},"StyleType":{"DisplayName":"Edwardian","SystemName":"Edwardian"},"LeaseType":{"DisplayName":"Freehold","SystemName":"Freehold"},"AgeType":null,"DescriptionType":{"DisplayName":"Style and Age","SystemName":"StyleAge"},"Name":null,"Notes":null},{"Gardens":1,"ParkingSpaces":0,"Garages":1,"DescriptionType":{"DisplayName":"Amenity","SystemName":"Amenity"},"Name":null,"Notes":null},{"Bedrooms":6,"Bathrooms":3,"Receptions":5,"Others":0,"DescriptionType":{"DisplayName":"Room Count","SystemName":"RoomCount"},"Name":null,"Notes":null},{"Features":[{"Order":1,"Feature":"Premier Road"},{"Order":2,"Feature":"Extensive Mature Gardens"},{"Order":3,"Feature":"Single Garage"},{"Order":4,"Feature":"Available Immediately"},{"Order":5,"Feature":"Driveway Parking"}],"DescriptionType":{"DisplayName":"Feature","SystemName":"Feature"},"Name":"Features","Notes":null},{"Text":"
Character four bedroom detached home situated on a generous plot estimated at 1/4 of an acre in one of the areas premier roads. uPVC double glazed windows, many original features such as rear aspect bay windows, solid wooden internal doors and a working fireplace. Extensive driveway parking. Single garage with light and power. Incredible secluded rear garden approximately 200 ft long

","DescriptionType":{"DisplayName":"SummaryText","SystemName":"SummaryText"},"Name":"SummaryText","Notes":null},{"Text":"
This is the marketing text for 76 Wokingham Road.  Everything about this house is amazing.

","DescriptionType":{"DisplayName":"Text","SystemName":"Text"},"Name":"Main Marketing","Notes":null},{"Rooms":[{"Order":0,"Name":"Bedroom One","Text":"3m x 2.3m (9' 10\" x 7' 7\") This is the text describing bedroom one. It is rear facing with a bay window and working fireplace","Images":[],"RoomDescriptionType":{"DisplayName":"Room","SystemName":"Room"}},{"Order":1,"Name":"Bedroom 2","Text":"3m x 1.5m (9' 10\" x 4' 11\") Has front and rear aspect windows along with a working fireplace. Wood floor throughout.","Images":[],"RoomDescriptionType":{"DisplayName":"Room","SystemName":"Room"}}],"DescriptionType":{"DisplayName":"Room","SystemName":"Room"},"Name":"Room","Notes":null},{"Tags":[{"Name":"older house"},{"Name":"premier road"}],"DescriptionType":{"DisplayName":"Tag","SystemName":"Tag"},"Name":"Tags","Notes":null}]

Cant we get  all description in just one format?

**Comment by dendle** [comment]
Hello Prashant,
The descriptions have varying data types; there is a DescriptionType field that describes what data it has.  Some are wordy descriptions, some are room counts.  Its not possible to 'flatten' these data types down as they are very different.

The API documentation describes the base class that holds data that all descriptions have.  You must use the description type to work out what type of description it is, in order to show the data correctly.

So, as an example, in the case of Style and Age, the description holds the style, age and lease type of the house in the StyleType, LeaseType and AgeType properties.

Regards,
Matt Dendle
