### ISSUE TITLE
Can't save room description

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#30]
I am calling the following URL:

https://api.dezrez.com/api/RoomDescription/save?agencyID=131

With the following data:

{"Name":"Room","PropertyId":"351108","Rooms":[{"Id":null,"Order":null,"Name":"A Room","Text":"Some room","RoomDescriptionType":{"SystemName":"Room"},"RoomMeasurements":[]}],"ForceUpdate":true}

And getting the following response:

{"Message":"Authorization has been denied for this request."}

I have tried adding the BranchId parameter as well but get the same result

**Comment by marc-harry** [comment]
Closing as this is the same issue as #25
