### ISSUE TITLE
Can't attach group to property in UAT

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#31]
I am calling the following URL:

https://core-api-uat.dezrez.com/api/property/519106/addgrouptoproperty?agencyID=4&BranchId=31901

And passing the following data:

{"Group":{"Id":"3341104"},"ForceUpdate":true}

And getting the following response:

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"619a4079-5b1e-43dd-8be9-359f453ded60","Details":"Error occured whilst invoking action AddGroupToProperty on controller PropertyController. This error has been logged.","ValidationErrors":null}

**Comment by marc-harry** [comment]
This endpoint is throwing an error due to the "OwnedSince" property not being provided. This is a required field on this endpoint.

Cheers,
Marc
