### ISSUE TITLE
Can't retrieve group offers in UAT environment

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#32]
I am calling a GET request on the following URL:

https://core-api-uat.dezrez.com/api/group/3341105/offers/received?agencyID=4&pageNumber=1&pageSize=20

And getting the following response:

{"Message":"Authorization has been denied for this request."}

**Comment by marc-harry** [comment]
Hi @geoffs3310,
This issue is due to the scope permissions on that particular endpoint. I have fixed the issue with this and it will be deployed to the UAT environment shortly.
Cheers,
Marc
