### ISSUE TITLE
Can't save room description in UAT environment

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#33]
I am doing a POST request to the following URL:

https://core-api-uat.dezrez.com/api/RoomDescription/save?agencyID=4

Passing the following data:

{"Name":"Room","PropertyId":"519106","Rooms":[{"Id":null,"Order":null,"Name":"A Room","Text":"Donec rutrum congue leo eget malesuada. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Curabitur aliquet quam id dui posuere blandit. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus suscipit tortor eget felis porttitor volutpat.","RoomDescriptionType":{"SystemName":"Room"},"RoomMeasurements":[]}],"ForceUpdate":true}

The API just returns null and the room doesn't get added

**Comment by marc-harry** [comment]
There are a couple of core concepts with the API, what is happening with the endpoint call above is the description is getting saved but it would be saved onto the Property with Id: 519106. 

This wouldn't appear on the marketing information for that property. As we use roles to store all the information contained within a single marketing cycle. You would need to provide the Sales Marketing Role Id to the data contracts roleId property for this description to be correctly added into the system and to be visible on the marketed property. If you navigate to a property within the software you will see the Sales Marketing Role Id as query parameter in the url.

The data you have provided though has been stored but it will only be used as a default description that is put onto new marketing roles if the property were withdrawn and then re-marketed, or was sold and then put onto the market again in the future.

More information about some of the core concepts of the API are outlined in the document linked below.

I hope this information helps.

[Dezrez Core Platform Domain Model](https://dezrezservices-my.sharepoint.com/personal/matthew_dendle_dezrez_com/_layouts/15/guestaccess.aspx?guestaccesstoken=wG26X6xJQpVALwVHGuzxMIvEDcpVUB%2fnOenxMxBrCxY%3d&docid=03c2d6f52b51747f4b7bd2562de2f2cec)

**Comment by tuscan88** [comment]
OK I think I understand now thanks
