### ISSUE TITLE
RoomDescription/save returns null in UAT environment

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#34]
I am doing a POST request to the following URL:

https://core-api-uat.dezrez.com/api/RoomDescription/save?agencyID=4&BranchId=31901

With the following data:

{"Id":3908813,"Name":"Room","Notes":null,"PropertyId":524602,"RoleId":6186602,"Rooms":[{"Id":0,"Order":0,"Name":"Living Room","Text":"Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt. Pellentesque in ipsum id orci porta dapibus. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Donec rutrum congue leo eget malesuada. Donec sollicitudin molestie malesuada.","RoomDescriptionType":{"SystemName":"Room"},"RoomMeasurements":[]},{"Id":0,"Order":1,"Name":"Kitchen","Text":"Curabitur aliquet quam id dui posuere blandit. Nulla porttitor accumsan tincidunt. Pellentesque in ipsum id orci porta dapibus. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Donec sollicitudin molestie malesuada. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Donec rutrum congue leo eget malesuada. Donec sollicitudin molestie malesuada.","RoomDescriptionType":{"SystemName":"Room"},"RoomMeasurements":[]}]}

The room descriptions get saved however the API just returns null rather than a proper response

**Comment by marc-harry** [comment]
Hi @geoffs3310,
I have just tested this example and it has worked successfully and returned the description that was created in the response. Is this something that is still happening for you?
Cheers,
Marc
