### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#38]
Is there a way either directly from Rezi or through the use of the API or other service that users can be instantly notified when a viewing gets created or cancelled for one of their properties?

**Comment by rjmacarthy** [comment]
HI @geoffs3310 there is SignalR into the API.  Therefore, such functionality should be available when connecting to the SignalR hub.

In the Rezi SPA we connect using the jQuery SignalR package as such:

```
$.connection.hub.url = Config.SignalRUrl;
$.connection.hub.qs = { jwtToken: this._authServiceInstance.AccessToken };

```

Where:

 `Config.SignalRUrl` = https://core-api-systest.dezrez.com/signalr/hubs

And

 `this._authServiceInstance.AccessToken` = Your API access token.

Once connected you should start to receive negotiations through web sockets of such events for appointments.

Whether this works with code flow authentication is something we are yet to test as it hasn't been raised as a question before.  If you do try and you are having problems please let us know.

Richard.
