### ISSUE TITLE
Property location not set correctly

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#39]
When trying to push properties to the portals that have been created through the API we are seeing a message saying "The property location has not been set correctly" (see screenshot [http://imgur.com/2iPimkw](http://imgur.com/2iPimkw)) Are you able to give any more information as to why this would be happening. We are passing through the various address fields when the property is being created are there any further steps that we need to do?

**Comment by rjmacarthy** [comment]
Hi @geoffs3310, this error will occur if the property does not have a Latitude or Longitude set.  You can fix this by amending the Location marker in the Location tab on the MarketingHub page you are on.

This can also be fixed/achieved using the API and the `api/address` endpoints.

These endpoints can also be used to integrate google maps and such extensions.

Once these values are set the property should be OK to start marketing.

Hope this helps.

Richard.
