### ISSUE TITLE
Refresh Token API error

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#4]
Hello,

We are trying to get the refresh token from the existing access token, but we are getting an error message as {"message":"{ \"error\": \"unauthorized_client\" }"}
In the documentation it is mentioned that client needs to registered for offline access, where we can change the offline access permission?
Are we missing any other permission?

Thanks,

**Comment by dendle** [comment]
Hello Prashant,

Refresh token do not apply to oauth2 clients that use the client auth flow.

If you need a new token, you just go through the auth process again, as there is no need to ask any human to enter their login details again.

I hope this makes sense.

Regards,
Matt

**Comment by prashant-v** [comment]
Hello,

Actually life of Access Token is very small, is there any way that we can increase life of Access token or is there any simple API is available to check whether perticular token is expire or not?
Because It doesn't seem good to call Oauth API to get API token every time before we call any of the property related API

Thanks

**Comment by dendle** [comment]
Hello Prashant,

The lifetime of all tokens is 2 hours, this gives us scope to revoke compromised tokens over a shorter period of time.

You can check when the token expires by looking at the reponse when you got the token, it should tell you exactly when you need to get a new token.

I hope this helps.

Regards,
Matt
