### ISSUE TITLE
Getting 401 unauthorised response on UAT when trying to update address centerpoint

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#41]
I am doing a put request to the following URL:

https://core-api-uat.dezrez.com/api/address/2490502/centerpoint?agencyID=4

Passing the following data:

{ 'Latitude': '53.17219190', 'Longitude': '-2.93177660', 'Altitude': '1' }

And getting the following response:

{"Message":"Authorization has been denied for this request."}

The scope for my Oauth token is:

impersonate_web_user property_write property_read event_read event_write people_read people_write document_write document_read

**Comment by dendle** [comment]
Hello Geoff,

I'm sorry its taken so long to get back to you.

This issue is due to a default security rule being applied - I have now fixed this in code, and it will make its way to UAT and Release over the next few days.

Thanks,
Matt
