### ISSUE TITLE
Image Resize

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#42]
Hi,
Is there a replacement image resizer for rezi? and does it return a https url?

Thanks
Dean

**Comment by dendle** [comment]
Hello Dean,

The images that are stored in rezi can be resized by using query string parameters.

For example, taking an image URL from the rezi api, and adding &width=200 will resize it to 200px wide.

Yes, the image URLs are accessible over HTTPS.

Thanks,
Matt
