### ISSUE TITLE
UAT Differance

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#43]
Hi,
On our live UI instance we have a description block called Services that we use for the tenant fees.  This block doesn't display on our UAT UI instance.

Is this a config change we need on the UAT instance?

Thanks
Dean

**Comment by rjmacarthy** [comment]
This sounds like a custom description type, they can be added on per request.  Do you need this added on?

If so please let us know your Agency ID and we can add it on for you.
