### ISSUE TITLE
General problem using UAT API

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#45]
Hi,

I haven't been working on this for a few months, and have just returned to my test code, which now doesn't work. The authentication stuff seems fine, but none of the API calls work. An example:

https://core-api-uat.dezrez.com/api/role/4687103/vendors?agencyID=125

{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"7c3b9d09-0787-4a01-9bb1-a423e76d3af1","Details":"Error occured whilst invoking action Vendors on controller RoleController. This error has been logged.","OwningTeam":null,"ErrorType":null,"ValidationErrors":null}

Apologies if I've missed a communication or am just doing something stupid.

**Comment by rjmacarthy** [comment]
HI @ewanmceachran 

Please can you try to specify a branchId in the query string for this request and see if this helps.

If still a problem, let us know.

Thanks

**Comment by ewanmceachran** [comment]
I didn't know what branchId to use, so I went with branchId=1. This did not help.

**Comment by rjmacarthy** [comment]
HI @ewanmceachran you can get a list of branch ids from `/agency` endpoint.

Alternatively,  I have looked up a branch Id for you of: 2336007

Please let me know if this helps.

Richard.

**Comment by ewanmceachran** [comment]
Nope, that didn't help, sorry.

**Comment by dendle** [comment]
I have AgencyID 125 as deleted on UAT.

is that the right agencyID?

Cheers,
Matt

**Comment by ewanmceachran** [comment]
That's the agency ID I've always used, yes. Perhaps it got deleted from lack of use?

**Comment by rjmacarthy** [comment]
Hi @ewanmceachran is this resolved for you now?

**Comment by ewanmceachran** [comment]
Yup, thanks
