### ISSUE TITLE
Failed to retrieve node context for agencyId 0

### ISSUE THREAD

**Issue by irishboy1976** [dezrez/DezrezCoreAPI#46]
Hi there, Just getting started on a property app for my client, my dev has hit a snag straight away and was wondering whether we are set up with the correct permissions/authorisation.

This is our request: https://github.com/ndxbxrme/vs-property/blob/master/src/server/dezrez.coffee

and we are receiving these errors:

_An error occurred when trying to create a controller of type \'PeopleController\'. Make sure that the controller has a parameterless public constructor_

and

_Failed to retrieve node context for agencyId 0_

Our first request works and we receive an access token but the second call throws the error

I was hoping you could shed some light.

Thanks in advance

**Comment by marc-harry** [comment]
Hi @irishboy1976,
In order for this request to be successful you need to add 'agencyId' as a query string parameter with the agency id for the customer you developing for, The endpoint should then return you a response.

Cheers,
Marc
