### ISSUE TITLE
Request restrictions (429 responses)

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#47]
Hi,

Could you tell me what restrictions there are on the Rezi UAT environment - and the live environment - in terms of request volume? I tried to load up all the historical data (for the fields that I needed) from UAT and after a while started getting 429 responses.

Ta

**Comment by marc-harry** [comment]
Hi @ewanmceachran,

There is a request limit on the API of 750 requests per hour. If you are exceeding that then that would be the reason for the 429 responses you are getting.

Cheers,
Marc
