### ISSUE TITLE
"Under Offer" properties

### ISSUE THREAD

**Issue by simmerz** [dezrez/DezrezCoreAPI#48]
Hi, trying to understand the Swagger UI docs, and failing. How would I go about getting a list of properties currently under offer/sale agreed?

**Comment by rjmacarthy** [comment]
Hi @simmerz the best way to do this would be using the property list endpoint, for example:

**POST**

`api/list/property?pageSize=25&pageNumber=1`

Using the following payload:

```
{
  "RoleStatuses": [
    "OfferAccepted"
  ],
  "RoleTypes": [
    "Selling"
  ],
  "Sort": "Price",
  "Order": "Descending",
  "Name": "InstructedProperties",
  "BranchId": 1
}
```

The role statuses array will allow you to filter properties in different statuses.

Hope that helps.
