### ISSUE TITLE
Errors switching to live environment

### ISSUE THREAD

**Issue by irishboy1976** [dezrez/DezrezCoreAPI#49]
OK, so we are trying to get this live key working, and we are hitting some errors.
 
Firstly when we tried with all the scopes provided: event_read event_write people_read people_write property_read property_write impersonate_web_user, it won’t even allow us to get an access token.
If we try it without the impersonate_web_user, it at least gets us past the token part. (we tried taking that out of the UAT setup we have and it broke, so I am assuming this is the problem)
 
OK so now we get in we have tried a pretty standard request (postman call below)
 
GET /api/people/findbyemail?emailAddress=******%40**********&amp;agencyId=**&amp;branchId=**** HTTP/1.1
Host: api.dezrez.com
Rezi-Api-Version: 1.0
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InZjXzBZSV8yWTNNUGdZbkU2OEcteXpWMHF5MCJ9.eyJpc3MiOiJodHRwczovL2F1dGguZGV6cmV6LmNvbS9Jc3N1ZXIiLCJhdWQiOiJSZXppQ2xpZW50QVBJIiwibmJmIjoxNDg2Mzk4NTIzLCJleHAiOjE0ODY0MDU3MjMsImNsaWVudF9pZCI6Ik1hbmNoZXN0ZXJNYWRlX1ZpdGFsc3BhY2VfTGl2ZSIsInNjb3BlIjpbImV2ZW50X3JlYWQiLCJldmVudF93cml0ZSIsInBlb3BsZV9yZWFkIiwicGVvcGxlX3dyaXRlIiwicHJvcGVydHlfcmVhZCIsInByb3BlcnR5X3dyaXRlIl0sIkFjY2Vzc0FnZW5jeUlkIjoiMzYifQ.kgjUR698Nes5IU9fCumbXMY8h_ku_mTqD7wRgGmEtUsRWmh1zik9uzGrf8bm39tEp-4Rw7PeIbAgJZF4cg3LnMiFmHDIdR3abSs6ZFIGiZnPz90NLCR0HGC7ou-aS_ZOvAGvFfvPs-wu9WtexVV6UqIuG_6HzaczDlKfK838vSgGpy422r5eO2_etm2YruOZkX6gk8ZBwJj_t9Ut3cwoIEb3WsX602CrBiuIquCXIlWnWb0doVj27eM-tZLOlUNIKxzcKSZ6BDVJU87CE0ZKuMU-vVKFcaVKCSUwwJddlGNh3MxMWIV_tChJgyonwLWaOhzSOkTk8Bkc1TN24SUFcA
Cache-Control: no-cache
Postman-Token: 59f1a72f-f955-7d71-a783-d6d6c9ad3d12 

This call is throwing this error:

{
  "Message": "An error has occurred. If this persists please contact us",
  "ErrorReference": "ec1cfa67-e462-4052-9c1f-f3b6f939ce24",
  "Details": "Error occured whilst invoking action GetPeopleWithEmailAddress on controller PeopleController. This error has been logged.",
  "OwningTeam": null,
  "ErrorType": null,
  "ValidationErrors": null
}

Thanks in advance for your input

**Comment by dendle** [comment]
Sorry for the delay in replying - is this still an issue for you?

I'm not sure if we've responded via another channel, so I'll close this issue for now - feel free to reply here and I'll re-open it and help you out.

Cheers,
Matt
