### ISSUE TITLE
Add person/people in Rezi system

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#5]
Hello,

We want to add person/people in Rezi system. so which API we should user?

Thanks

**Comment by dendle** [comment]
Hello Prashant,

You'll need to add a group, with members.

A person in dezrez is always a member of a group.

Here is the relevant endpoint:
http://api.dezrez.com/Help/Api/POST-api-group-addgroup

Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

By passing members information i can add person to rezi system, but how I would get the personid of inserted member in group?

**Comment by dendle** [comment]
Hello Prashant,

Sorry for the delay in my reply, I've been out of the office.

As a response to creating a group, you get back the group ID.

You can then use this to get the group at the get group endpoint, and see the personId inside that group.

I hope this helps!

Regards,
Matt
