### ISSUE TITLE
Withdrawn Property still live

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#50]
Hi,
We have a property that has been 'withdrawn'. The rezi UI correctly shows that but in the API the property is still shown as InstructionToSell.

Is this a bug or is there another field we should be looking at to override this flag?

PropertyID: 3860813

Thanks
Dean

**Comment by rjmacarthy** [comment]
Hi, please let us know which agency ID you are using and which endpoint in the API you are using where the wrong data is showing.

**Comment by prashant-v** [comment]
Hello,

We are using the AgencyID : 84 and we are using the following endpoint API to get the properties.
https://api.dezrez.com/api/simplepropertyrole/search?AgencyId=84
and to get property details by role we are using following API
https://api.dezrez.com/api/simplepropertyrole/3860813?AgencyId=84

Please note :  3860813 is property role id.

Thanks,
Nitin

**Comment by dzy969** [comment]
Hi - Any update on this issue?

**Comment by rjmacarthy** [comment]
This was a small data inconsistency, which should be resolved now.  

Richard.
