### ISSUE TITLE
using list/groupidsfiltered

### ISSUE THREAD

**Issue by neilrbanks** [dezrez/DezrezCoreAPI#51]
Hi calling
https://api.dezrez.com/api/list/groupidsfiltered/?agencyId=xxx

results in 
  "Message": "No HTTP resource was found that matches the request URI 'https://api.dezrez.com/api/list/groupidsfiltered/?agencyId=xxx'.",
  "
calling without agencyid finds the method but returns

"ExceptionMessage": "Failed to retrieve node context for agencyId 0 also providing in body produces same error. How do I use this method propertyidsfiltered also behaves the same

Thanks

**Comment by rjmacarthy** [comment]
Hi Neil,

The endpoint you need is `/api/list/groups/groupidsfiltered` not `/api/list/groupidsfiltered`

Richard.

**Comment by neilrbanks** [comment]
ok cheers that's working

Thanks Neil
