### ISSUE TITLE
Is it possible to update summary, main marketing text and features before a property has been put on the market?

### ISSUE THREAD

**Issue by tuscan88** [dezrez/DezrezCoreAPI#54]
I am using the API to create a property in Rezi and so as part of that process I use the following API methods to add the summary, main marketing text and features:

// Summary
POST to api/TextDescription/save
data = [
	'Text' => 'Some summary text',
	'Type' => [
		'Name' => 'SummaryText',
		'SystemName' => 'SummaryText'
	],
	'Name' => 'SummaryText',
	'ForceUpdate' => true,
	'Id' => [property rezi id],
	'RoleId' => [property role id]
];

// Main marketing text
POST to api/TextDescription/save
data = [
	'Text' => 'Some marketing text',
	'Type' => [
		'Name' => 'Text',
		'SystemName' => 'Text'
	],
	'Name' => 'Main Marketing',
	'ForceUpdate' => true,
	'Id' => [property rezi id],
	'RoleId' => [property role id]
];

// features
POST to api/FeatureDescription/Save
[
	'Id' => $property->rezi_features_id,
	'Name' => 'Features',
	'RoleId' => $property->rezi_selling_role_id,
	'ForceUpdate' => true,
	'Features' => [
		[
			'Id' => null,
			'Order' => 1,
			'Name' => 'Some feature'
		],
		[
			'Id' => null,
			'Order' => 1,
			'Name' => 'Another feature'
		],
	]
];

All of three of these calls work the first time I call them with a brand new property and the data is stored in Rezi however before the property is put on the market there doesn't seem to be a way to view this information. It's only once that property has been put on the market that the descriptions and features tab becomes available. 

So my first question is how come I'm not able to view this information before putting the property on the market? Is there a way to do view it when viewing the property in Rezi that I'm not aware of? 

Secondly if I try and do these calls again before the property has been put on the market in order to update the information they all fail. Is there a way to update the summary, main marketing text and features both through the API and through the Rezi control panel  before the property has been put on the market?

Thanks

**Comment by dendle** [comment]
Hello Geoff,

Sorry for the delay here - is this still an issue for you?

The mix-up might be that we store descriptions on a property, as well as the roles the property is in.

For example, see the case I just closed with #60.

Also, where are you reading them from to say that they are not appearing?

I'll close this ticket as old - if this is still an issue, go ahead and reply and I'll re-open it.

Cheers,
Matt
