### ISSUE TITLE
Using list/groupinterests

### ISSUE THREAD

**Issue by neilrbanks** [dezrez/DezrezCoreAPI#55]
Hi

I'm calling
https://api.dezrez.com/api/list/groupinterests?agencyId=xxx&pageSize=100

with body of 
{
      "RoleTypes": ["SearchingForSale"]
}
 which is returning nothing but when I make the same call without a filter and iterate the results there are multiple entries  with that roletype am I missing something?

Thanks

**Comment by dendle** [comment]
Hello Neil,

I appreciate this might be a late response, so I hope we've responded on another channel - if not, please let me know if this issue is still ongoing.

I can get the filter to work here, so I'm hoping this is a bug we've fixed.

Cheers,
Matt
