### ISSUE TITLE
https://api.dezrez.com/api/list/property/propertyidsfiltered?agencyId=xxx

### ISSUE THREAD

**Issue by neilrbanks** [dezrez/DezrezCoreAPI#56]
Hi calling above api  with body of {} appears to be returning a set of propertyids which when calling

https://api.dezrez.com/api/property/xxxxxxxx/?agencyId=106
 returns

{
  "Message": "Property with id = xxxxxxx not found"
}

**Comment by dendle** [comment]
Hello Neil,

This may be a data issue, where the list filters are returning references to properties that are deleted or are not in an active state.

However, to make sure this is the case, can you provide us with a propertyId, and which JSON property from the list endpoint results you got it from.

Thanks,
Matt

**Comment by neilrbanks** [comment]
Hi Matt

Here are an example of the propertyids coming back but trying to retrieve any of these via

https://api.dezrez.com/api/property/xxxxxxxx?agencyId=xxx
results in

{
  "Message": "Property with id = xxxxxxxx not found"
}

  1892059,
  1892063,
  1892070,
  1892086,
  1892099,
  1892149,
  1892179,
  1892213,
  1890956,
  1889406,
  1888340,
  1894889,
  5021814,
  4523211,
  5121911

I am currently iterating through /list/property results which does contain usable ids

I have just come across another issue using
/list/groups/groupidsfiltered

To obtain a list of people in a group but have found some cases the groupid on the properties Owns role isn’t there any idea why that would be the case

Cheers Neil

**Comment by dendle** [comment]
Hello Neil,

I've just checked the code and the endpoints name is misleading.

The IDs are not property IDs - they are the RoleIds of sales and lettings roles, which are attached to properties.

Use the Get Role endpoint with those IDs, and that should give you the information you are looking for.

I'll see if I can update the documentation to make this endpoint name less misleading.

Thanks,
Matt

**Comment by neilrbanks** [comment]
Hi Matt

Ok cheers I can work with that

Thanks Neil

**Comment by dendle** [comment]
Awesome. I'll close this off.

**Comment by neilrbanks** [comment]
Hi matt do you have any idea on the groupidsfiltered issue:-

Cheers Neil

I have just come across another issue using
/list/groups/groupidsfiltered

To obtain a list of people in a group but have found some cases the groupid on the properties Owns role isn’t there any idea why that would be the case

**Comment by dendle** [comment]
Think thats a different case there - you are not just getting Id's back, you are getting a data contract back that actually says GroupId and PersonIds, so there is no ambiguity there.

In this case, if you are getting 404s or missing references, this is because that entity has been deleted in our software.

However, if this is happening for the majority of calls, esp. for active stock, this might be something else.

If its just a small number, they've been deleted.

HTH,
Matt

**Comment by neilrbanks** [comment]
Hi Matt Yes I do deserialize and walk the data structure – just looking at the examples I have been given and they appear to be at status Valued don’t know if that’s just a coincidence and a number of let properties.

Thanks Neil

**Comment by neilrbanks** [comment]
Hi Matt

Got some examples which have a groupid on Owns Role but no matching entry in groupidsfiltered and there are quite alot

Thanks Neil

Some examples from sales
204230  Active   Exchanged
203315  Active   Exchanged
200141  Active   InstructionToSell
202586  Active   InstructionToSell
201890  Active   InstructionToSell
201329  Active   InstructionToSell
200769  Active   InstructionToSell
205370  Active   OfferAccepted
200608  Active   OfferAccepted
199889  Active   Valued
200104  Active   Valued

Some examples from lettings
200968  Active   InstructionToLet
588502  Active   InstructionToLet
201014  Active   InstructionToLet
200000  Active   InstructionToLet
515701  Active   InstructionToLet
201754  Active   Valued
200920  Active   Valued

**Comment by thomassb** [comment]
@dendle These end point names are terrible, the one you mentioned by op is still called propertyidsfiltered.
good thing I have a lot of spagetti to throw.

Is there any proper documentation for this API other then the very missleading swagger doc?

**Comment by ajonesgh** [comment]
Hi thomassb 

Here is the API help page https://api.dezrez.com/help

If you have any further questions please feel free to drop us an email at developer.questions@dezrez.com.

Thanks
Adam
