### ISSUE TITLE
Field mappings

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#58]
From an integration with a previous version of DezRez we have the following fields on a 'contact':

Active
Deleted
Branch Code
Status Text
Financial
Financial Text
Grade ID
Reason
Reason Text
Updated Date

Could you let me know if there are analogues in Rezi and, if so, how to get them? I can't face any more random poking at your API in the hope that they'll drop out.

Thanks

**Comment by DezrezEnterpriseTeam** [comment]
Hi Ewan, see below for some useful info relating to these items:

Active
https://api.dezrez.com/group/{id}
SystemStatus.Name == "Active"

Deleted
https://api.dezrez.com/group/{id}
SystemStatus.Name == "Archived"

Branch Code
https://api.dezrez.com/group/{id}

Status Text
https://api.dezrez.com/group/{id}
Roles[0].FinancialStatus == {Id: 384, Name: "Spoken to our advisor", SystemName: "SpokenToOurAdvisor"}
Where Roles[0] is the searching role

Financial
N/A

Financial Text
N/A

Grade ID
https://api.dezrez.com/group/{id}
Grade == {Id: 400, Name: "Two", SystemName: "Two"}

Reason
N/A

Reason Text
https://api.dezrez.com/group/{id}
Description

Updated Date
N/A

**Comment by ewanmceachran** [comment]
Thank you for the response - very helpful
