### ISSUE TITLE
API usage restrictions

### ISSUE THREAD

**Issue by ewanmceachran** [dezrez/DezrezCoreAPI#59]
Hi,

I've been working to a limitation on the API usage for development, something like 750 calls in an hour. Are there similar such restrictions on calls to live systems?

**Comment by dendle** [comment]
Hello Ewan,

Sorry for the delay in the response - I'm not sure if we have answered you via another channel, but yes, by default, 750 per hour is the rate limit.  However, we can change this for partners if it poses problems for a particular integration.

Give me a shout if you want to discuss further.

Cheers,
Matt
