### ISSUE TITLE
Add Group API

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#6]
Hello,

I am executing Add group API : https://core-api-uat.dezrez.com/Help/Api/POST-api-group-addgroup
but I am facing an error as {"Message":"Authorization has been denied for this request."}

Can you guide which permission I need to use for add group and add group member?

Thanks,

**Comment by dendle** [comment]
Hello Prashant,

Sorry fro the delay, I have been on annual leave.

Let me review the required scopes, and make sure you have access to request the appropriate scope.

Cheers,
Matt

**Comment by dendle** [comment]
Hello Prashant,

I have fixed this issue, but I'm afraid it will need a code deployment to fix.

I've started the process and will let you know when its done.

Cheers,
Matt

**Comment by dendle** [comment]
The code deployment is on its way to UAT, and should be there in roughly 30 minutes.

Just to confirm, you shouldnt need any code changes, as you already have person_write scope - this is all that is needed.

Cheers,
Matt
