### ISSUE TITLE
List of viewings

### ISSUE THREAD

**Issue by dzy969** [dezrez/DezrezCoreAPI#61]
Hi,
What would be the easiest way to get a list of all the viewing appointments that took place in the last x days.

Is there a easier way than cycling through all the property roles and getting the appointments for one?

Cheers
Dean

**Comment by dendle** [comment]
Hi Dean,
I think the event list endpoint would be best - you can filter the returned types to just viewings, and can also supply a date range filter.

Here is the API:
http://api.dezrez.com/Help/Api/POST-api-list-events_pageSize_pageNumber

Hope this helps,
Cheers,
Matt
