### ISSUE TITLE
Issue- accessing APIs

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#62]
Hello Team,

I have been facing issue of 500 (Internal server error) while accessing APIs since Friday. Here is the details you can find sample error details:

URL(POST)-  https://api.dezrez.com/api/simplepropertyrole/search?AgencyId=122
Request body- {'PageSize': 34000,'PageNumber': 1, 'IncludeStc':'true'}
Response returned- The remote server returned an error: (500) Internal Server Error.

Can you look into this? Thanks for your help in advance!

Thanks,
Prashant

**Comment by DezrezEnterpriseTeam** [comment]
Hi Prashant, the agency with ID 122 is not an active agency using Rezi at this time. Please liaise directly with your client and if this should not be the case, please ask them to contact their Dezrez account manager to resolve.

**Comment by prashant-v** [comment]
Oh! Sorry for wrong URL.

Can you please check for this URL: https://core-api-uat.dezrez.com/api/simplepropertyrole/search?AgencyId=122 ?

Sorry for hassle. Awaiting for your response!

Thanks,
Prashant

**Comment by DezrezEnterpriseTeam** [comment]
Hi Prashant, due to an issue with our test environment we had to rebuild the environment and as a result, remove all test agency data. Unfortunately this means your test data is no longer available to you. I apologise for this. We will create a new agency and seed it with some dummy data from this agency's old software. Once complete, we will be in touch.

**Comment by DezrezEnterpriseTeam** [comment]
Hi Prashant, a new agency has been set up on our UAT environment with an Agency ID of 317. All other details you have used in the past should remain the same.

Apologies again for the inconvenience.

**Comment by prashant-v** [comment]
Thanks for your help. In addition to this, can you recover data related to viewings as well, I wanted to play with viewings and their feedback?

Thanks
Prashant

**Comment by dzy969** [comment]
Can you populate agencyid 317 with data from our live installation or even from our old dezrez system.  We need some test data really otherwise its really going to waste a lot of time recreating it manually.

**Comment by DezrezEnterpriseTeam** [comment]
Hi both, agency 317 was populated with data from the old Dezrez system when it was recreated. There are 100s of properties and 1000s of clients in there for you to work with. Can you let us know what you are seeing to make you think there is no data in there? Thanks.

**Comment by dzy969** [comment]
Hi - I cant see anything in Rezi, Did you switch our https://rezi-web-uat.dezrez.com logins over to 317? and are the API credentials the same as before?

**Comment by DezrezEnterpriseTeam** [comment]
Please can you drop an email to developer.questions@dezrez.com with the credentials you are using so that we can check they are mapped correctly to the new agency.
