### ISSUE TITLE
Client flow - Could not map the current identity to a user!

### ISSUE THREAD

**Issue by alan-macdonald-espc** [dezrez/DezrezCoreAPI#64]
Hi,

I'm hoping you can help: I'm attempting to write a server-side app which accesses the Dezrez API on behalf of a client, and although I'm able to authenticate and get an OAuth 2 access token, whenever I make a request to the API using that token, I get the same error returned: `Could not map the current identity to a user!`

I'm using the OAuth client flow and a scope of `property_read`, and when I send the authentication request I get an access token returned.

For testing purposes, I've been using Postman and it refers to the client flow as Grant Type "Client Credentials".   I submit the authentication request and get an access token returned, then create a `GET /api/property/<propertyId>` request and include the `agencyId` on the query string, add an `Authorization` header with the access token value, a `Rezi-Api-Version` header set to `1.0`, and a `Content-Type` header set to `application/json`.  When I submit that request I get an exception message returned saying it cannot map the current identity to a user.  Other requests to the API (e.g. `GET /api/Agency`) return the same exception.

Could you tell me what I'm missing or doing wrong, please?

Thanks,
Alan

**Comment by matt-lethargic** [comment]
Hi Alan,

I'll look into this now and get you a working solution.
And sorry for the delay in getting back to you.

**Comment by matt-lethargic** [comment]
Could you send me:

- Url you are using
- ClientId
- Email address of account
- Scope

**Comment by alan-macdonald-espc** [comment]
Thanks Matt.   I've sent you an email with the details so you should receive it shortly.

**Comment by ajonesgh** [comment]
Hi Alan

I hope the email I sent last Friday has resolved the issue you were having. If you have any further questions please feel free to drop us an email to developer.questions@dezrez.com.

Thanks
Adam
