### ISSUE TITLE
Start Marketing - API

### ISSUE THREAD

**Issue by BYM-Henry** [dezrez/DezrezCoreAPI#68]
Hi,

We have been told by an agent that they have a button called 'Start Marketing' in Rezi,which is pressed to indicate a property has gone on market. Whilst I can see an Instructed Date against a property on the API, is there a value which corresponds to that button being pressed for a property.

Please let me know if any of this is unclear.

Many Thanks,

Henry F
BriefYourMarket

**Comment by ajonesgh** [comment]
Hi Henry

When that button is pressed an event is created against the properties marketing role. You can retrieve these events by using the below endpoint. There are various filters you can use to drill down to the type of events you need

https://api.dezrez.com/Help/Api/GET-api-role-id-events_pageSize_pageNumber_branchId_from_to_type[0]_type[1]_eventCategoryType_excludedTypes[0]_excludedTypes[1]_includeDrafts_excludeRevised

Event Types can be found using the endpoint below
GET /api/enum?typeName=EventType

Hope this helps

Thanks
Adam

**Comment by BYM-Henry** [comment]
Thanks Adam,

Just one more quick thing, are any events types custom per agent, or is that just a set list of event types.

Thanks,

Henry

**Comment by dendle** [comment]
It is possible to add custom event types to an agency. A request would need to made to the account management team.

Thanks
Adam

Adam Jones
Senior Developer
[http://www.dezrez.com/drapp/estateagents/emailsig2/logoweb.jpg]<http://www1.dezrez.com/>

[Description: Subscribe to us on Facebook]<https://www.facebook.com/dezrezsoftware/>
[Description: Subscribe to us on Twitter]<https://twitter.com/dezrezsoftware>
[Description: Subscribe to us on LinkedIn]<https://www.linkedin.com/company/dezrez>
[Description: Subscribe to us on Youtube]<https://www.youtube.com/user/dezrezsoftware>
[Description: Subscribe to us on Youtube]<https://plus.google.com/+dezrez>
[Awards][Awards]
[http://www.dezrez.com/drapp/estateagents/emailsig2/em2.jpg]
Adam.Jones@dezrez.com
[http://www.dezrez.com/drapp/estateagents/emailsig2/house.jpg]
Ethos, Kings Road, Swansea, SA1 8AS


All information included within this message, including attachments is of a confidential nature, possibly exempt from disclosure under applicable law, and intended only for named recipients. If you are not a named recipient; access, reading, copying, disclosure or re-use of information is strictly prohibited, and possibly unlawful.
If you have received this message in error, please immediately delete this message from your system. Any views or opinions expressed in this message, are solely those of the author, and do not necessarily represent the views of the company.

GDPR Disclaimer: Anything we state regarding GDPR is based upon our understanding of the legislation and may be subject to change as the legislation develops. We offer our observations only and these do not constitute advice. We recommend that agents obtain their own advice as we cannot be aware of all personal data that they hold, how it has been collected or the agent’s privacy and data handling policies – these are all important issues under GDPR which the agent must address. Whilst we provide software that assists the agent in complying with GDPR, the agent must address.

**Comment by ajonesgh** [comment]
It is possible to add custom event types to an agency. A request would need to be made to the account management team.

Thanks
Adam
