### ISSUE TITLE
Marketing Consent Fields

### ISSUE THREAD

**Issue by BYM-Henry** [dezrez/DezrezCoreAPI#69]
Hi All,

We currently receive these Marketing values for each Contact Items:

ACTIVE
BOUNCING
UNSUBSCRIBED MARKETING
UNSUBSCRIBED ALL

However from speaking to an agent they seem to have these values on the front end:

Marketing Allowed
Bouncing
Transactional Only
Do Not Contact

Would you be able to confirm if these match up like so:

Marketing Allowed | ACTIVE
Bouncing                | BOUNCING
Transactional Only  | UNSUBSCRIBED MARKETING
Do Not Contact      | UNSUBSCRIBED ALL

Many Thanks,

Henry Fitch

**Comment by griff-10** [comment]
Hi Henry, 

I can confirm that the marketing values for each contact item are correctly matched up in your previous comment: 

Marketing Allowed - Active
Transactional Only - UnsubscribedMarketing
Do Not Contact - UnsubscribedAll
Bouncing  - Bouncing 

If you have any further questions please do not hesitate to get in touch.

Thanks
Ant
