### ISSUE TITLE
Add member to group API

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#7]
Hello,

I have checked the details of adding member to group : https://core-api-uat.dezrez.com/Help/Api/PUT-api-group-id-addgroupmember
This accepts AddGroupPersonCommandDataContract i.e. https://core-api-uat.dezrez.com/Help/ResourceModel?modelName=AddGroupPersonCommandDataContract

I want to pass the PrimaryTelephone along with this request. How I could store the PrimaryTelephone in Rezi system

Thanks

**Comment by marc-harry** [comment]
Hi @prashant-v,

On the AddGroupPersonCommandDataContract there is a list property called ContactItems if you add a [https://core-api-uat.dezrez.com/Help/ResourceModel?modelName=ContactItemSaveCommandDataContract](https://core-api-uat.dezrez.com/Help/ResourceModel?modelName=ContactItemSaveCommandDataContract) to that list with Type with SystemName = "Telephone" and Value set to that of the phone number, that will be stored as the primary telephone number for that newly added member of the group

Thanks,
Marc
