### ISSUE TITLE
Fetch Applicant Viewings by batch

### ISSUE THREAD

**Issue by sofk91** [dezrez/DezrezCoreAPI#70]
Hi team,

Is there a way to retrieve viewings by batch, rather than requiring the ID?
(GET /api/Viewing/{id})

**Comment by ajonesgh** [comment]
Hi Sofiane
 
I think the event list endpoint would be best - you can filter the returned types to just viewings.

Here is the API:
http://api.dezrez.com/Help/Api/POST-api-list-events_pageSize_pageNumber

Hope this helps,
Cheers,
Adam
