### ISSUE TITLE
Add Group API 

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#8]
Hello,

I am getting an error while adding group to system
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"d80df059-a7e8-4a6e-83ba-641bbbc62250","Details":"Error occured whilst invoking action AddGroup on controller GroupController. This error has been logged.","ValidationErrors":null}
Can you please check the same?

Thanks,

**Comment by dendle** [comment]
We are currently investigating this error - I'll update you ASAP.

Regards,
Matt

**Comment by dendle** [comment]
Hello Prashant,

Could you confirm this is still happening?

If it is, could you please give me the details of the request you made to the API, including the full URL and the JSON.

I cannot seem to replicate the issue.

Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

yes I am still facing a same issue. sent you an email about the same

Thanks,

**Comment by dendle** [comment]
I'm investigating this now, and will get back to you ASAP.

Regards,
Matt

**Comment by dendle** [comment]
Hello Prashant,

When creating a new group, that group **must** have group members - you are attempting to add a group with no members, which I believe is causing the error.

These group members can be specified in the data contract.

I hope this helps,
Cheers,
Matt

**Comment by prashant-v** [comment]
Hello,

Even passing the member details we are getting a same error
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"7c2445d6-0e11-42f9-8fb2-4fef812c8846","Details":"Error occured whilst invoking action AddGroup on controller GroupController. This error has been logged.","ValidationErrors":null}

sent you details of request

**Comment by dendle** [comment]
Hello Prashant,

I'm looking at this issue now, and will get back to you ASAP.

Cheers,
Matt

**Comment by marc-harry** [comment]
Hi @prashant-v,

When saving group the members passed either needs to contain just the Id of an existing person that exists in Rezi on another group or the member details you send us as well as the name require the gender property to be set. If this is unknown you can send "NotSpecified".

Cheers,
Marc

**Comment by prashant-v** [comment]
Hello,

We tried with passing gender as "NotSpecified" but still getting the same error
{"Message":"An error has occurred. If this persists please contact us","ErrorReference":"e0cce764-da6a-48d3-aa69-3d0bf0855e4e","Details":"Error occured whilst invoking action AddGroup on controller GroupController. This error has been logged.","ValidationErrors":null}

Thanks

**Comment by dendle** [comment]
Hi Prashant,

Something still doesn't look right with the data you're sending up;

Can you double check the format of the data contract? or send it through to me again, with the error code?

Also, it might be worth using the software (I gave Dean a login) and looking at the network requests that it makes, and copy that - as this works, and is calling the same API.

Cheers,
Matt

**Comment by dendle** [comment]
Sorry, I accidentally closed this!
