### ISSUE TITLE
Adding identity to person

### ISSUE THREAD

**Issue by prashant-v** [dezrez/DezrezCoreAPI#9]
Hello

I am using the following API https://core-api-dev.dezrez.com/Help/Api/POST-api-identity-Add_personId
to add identify to rezi user but getting an error as
  {"Message":"An error has occurred. If this persists please contact us","ErrorReference":"b13f244a-8d5b-4662-a2e1-13cfd8840989","Details":"Error occured whilst invoking action AddIdentityToPerson on controller IdentityController. This error has been logged.","ValidationErrors":null}

can you please check the same?

Thanks

**Comment by dendle** [comment]
Yes, I suspect this is another permission issue - I will update you ASAP.

Regards,
Matt

**Comment by dendle** [comment]
Hello Prashant,

I've just fixed thi s issue in code, and will let you know when its available in the UAT API.

Thank you for your patience.

Regards,
Matt
